name: mymemories
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  sqflite: ^2.3.0
  image_picker: ^1.0.4
  location: ^5.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
